export enum OrderStatus {
  CREACION_PEDIDO = "CREACION_PEDIDO",
  ESPERA_DISPONIBILIDAD = "ESPERA_DISPONIBILIDAD",
  CANCELADO_POR_VENDEDOR = "CANCELADO_POR_VENDEDOR",
  PAGO_PENDIENTE = "PAGO_PENDIENTE",
  PROCESANDO = "PROCESANDO",
  ENVIADO = "ENVIADO",
  RECIBIDO = "RECIBIDO",
}
